services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./docker/web/DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - db # 依賴數據庫服務
    environment:
      TZ: Asia/Taipei
  db:
    # image: mysql:latest
    container_name: db
    build:
      context: ./
      dockerfile: ./docker/db/DockerFile
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: taipei_trip
      MYSQL_ROOT_PASSWORD: '0973'
    ports:
      - "3306:3306"
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/DockerFile
    ports:
      - 80:80
      # - 443:443
    depends_on:
      - db # 依賴數據庫服務
    environment:
      TZ: Asia/Taipei
volumes:
  db_data: