version: "3.8"  # optional since v1.27.0
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web/DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - db # 依賴數據庫服務
    environment:
      - TZ=Asia/Taipei
  db:
    # image: mysql:latest
    build:
      context: ./docker/db/
      dockerfile: ./DockerFile
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: taipei_trip
      MYSQL_ROOT_PASSWORD: '0973'
    ports:
      - "3307:3306"
volumes:
  db_data: